<?php


/**
 * This class adds structure of 'volunteer' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Apr 28 21:22:12 2016
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class VolunteerMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.VolunteerMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(VolunteerPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(VolunteerPeer::TABLE_NAME);
		$tMap->setPhpName('Volunteer');
		$tMap->setClassname('Volunteer');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('LAST_NAME', 'LastName', 'VARCHAR', false, 255);

		$tMap->addColumn('FIRST_NAME', 'FirstName', 'VARCHAR', false, 255);

		$tMap->addColumn('ADDRESS_LINE', 'AddressLine', 'VARCHAR', false, 255);

		$tMap->addForeignKey('CITY_ID', 'CityId', 'INTEGER', 'city', 'ID', false, null);

		$tMap->addForeignKey('STATE_ID', 'StateId', 'INTEGER', 'state', 'ID', false, null);

		$tMap->addForeignKey('ZIPCODE_ID', 'ZipcodeId', 'INTEGER', 'zipcode', 'ID', false, null);

		$tMap->addColumn('TELEPHONE_HOME', 'TelephoneHome', 'VARCHAR', false, 128);

		$tMap->addColumn('TELEPHONE_CELL', 'TelephoneCell', 'VARCHAR', false, 128);

		$tMap->addColumn('TELEPHONE_WORK', 'TelephoneWork', 'VARCHAR', false, 128);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', false, 255);

		$tMap->addColumn('CHURCH', 'Church', 'VARCHAR', false, 255);

		$tMap->addColumn('CITY_AREA', 'CityArea', 'VARCHAR', false, 255);

		$tMap->addForeignKey('SERVICE_ID', 'ServiceId', 'INTEGER', 'service', 'ID', false, null);

	} // doBuild()

} // VolunteerMapBuilder
