<?php

/**
 * Base class that represents a row from the 'client' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Apr 28 21:22:12 2016
 *
 * @package    lib.model.om
 */
abstract class BaseClient extends BaseObject  implements Persistent {


  const PEER = 'ClientPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ClientPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the last_name field.
	 * @var        string
	 */
	protected $last_name;

	/**
	 * The value for the first_name field.
	 * @var        string
	 */
	protected $first_name;

	/**
	 * The value for the parent_guardian_name field.
	 * @var        string
	 */
	protected $parent_guardian_name;

	/**
	 * The value for the address_line field.
	 * @var        string
	 */
	protected $address_line;

	/**
	 * The value for the city_id field.
	 * @var        int
	 */
	protected $city_id;

	/**
	 * The value for the state_id field.
	 * @var        int
	 */
	protected $state_id;

	/**
	 * The value for the zipcode_id field.
	 * @var        int
	 */
	protected $zipcode_id;

	/**
	 * The value for the telephone1 field.
	 * @var        string
	 */
	protected $telephone1;

	/**
	 * The value for the telephone2 field.
	 * @var        string
	 */
	protected $telephone2;

	/**
	 * The value for the school field.
	 * @var        string
	 */
	protected $school;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the family_size field.
	 * @var        int
	 */
	protected $family_size;

	/**
	 * The value for the city_area field.
	 * @var        string
	 */
	protected $city_area;

	/**
	 * The value for the service_id field.
	 * @var        int
	 */
	protected $service_id;

	/**
	 * @var        City
	 */
	protected $aCity;

	/**
	 * @var        State
	 */
	protected $aState;

	/**
	 * @var        Zipcode
	 */
	protected $aZipcode;

	/**
	 * @var        Service
	 */
	protected $aService;

	/**
	 * @var        array ClientVolunteerMap[] Collection to store aggregation of ClientVolunteerMap objects.
	 */
	protected $collClientVolunteerMaps;

	/**
	 * @var        Criteria The criteria used to select the current contents of collClientVolunteerMaps.
	 */
	private $lastClientVolunteerMapCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseClient object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [last_name] column value.
	 * 
	 * @return     string
	 */
	public function getLastName()
	{
		return $this->last_name;
	}

	/**
	 * Get the [first_name] column value.
	 * 
	 * @return     string
	 */
	public function getFirstName()
	{
		return $this->first_name;
	}

	/**
	 * Get the [parent_guardian_name] column value.
	 * 
	 * @return     string
	 */
	public function getParentGuardianName()
	{
		return $this->parent_guardian_name;
	}

	/**
	 * Get the [address_line] column value.
	 * 
	 * @return     string
	 */
	public function getAddressLine()
	{
		return $this->address_line;
	}

	/**
	 * Get the [city_id] column value.
	 * 
	 * @return     int
	 */
	public function getCityId()
	{
		return $this->city_id;
	}

	/**
	 * Get the [state_id] column value.
	 * 
	 * @return     int
	 */
	public function getStateId()
	{
		return $this->state_id;
	}

	/**
	 * Get the [zipcode_id] column value.
	 * 
	 * @return     int
	 */
	public function getZipcodeId()
	{
		return $this->zipcode_id;
	}

	/**
	 * Get the [telephone1] column value.
	 * 
	 * @return     string
	 */
	public function getTelephone1()
	{
		return $this->telephone1;
	}

	/**
	 * Get the [telephone2] column value.
	 * 
	 * @return     string
	 */
	public function getTelephone2()
	{
		return $this->telephone2;
	}

	/**
	 * Get the [school] column value.
	 * 
	 * @return     string
	 */
	public function getSchool()
	{
		return $this->school;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [family_size] column value.
	 * 
	 * @return     int
	 */
	public function getFamilySize()
	{
		return $this->family_size;
	}

	/**
	 * Get the [city_area] column value.
	 * 
	 * @return     string
	 */
	public function getCityArea()
	{
		return $this->city_area;
	}

	/**
	 * Get the [service_id] column value.
	 * 
	 * @return     int
	 */
	public function getServiceId()
	{
		return $this->service_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ClientPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [last_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setLastName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->last_name !== $v) {
			$this->last_name = $v;
			$this->modifiedColumns[] = ClientPeer::LAST_NAME;
		}

		return $this;
	} // setLastName()

	/**
	 * Set the value of [first_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setFirstName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->first_name !== $v) {
			$this->first_name = $v;
			$this->modifiedColumns[] = ClientPeer::FIRST_NAME;
		}

		return $this;
	} // setFirstName()

	/**
	 * Set the value of [parent_guardian_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setParentGuardianName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->parent_guardian_name !== $v) {
			$this->parent_guardian_name = $v;
			$this->modifiedColumns[] = ClientPeer::PARENT_GUARDIAN_NAME;
		}

		return $this;
	} // setParentGuardianName()

	/**
	 * Set the value of [address_line] column.
	 * 
	 * @param      string $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setAddressLine($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address_line !== $v) {
			$this->address_line = $v;
			$this->modifiedColumns[] = ClientPeer::ADDRESS_LINE;
		}

		return $this;
	} // setAddressLine()

	/**
	 * Set the value of [city_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setCityId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->city_id !== $v) {
			$this->city_id = $v;
			$this->modifiedColumns[] = ClientPeer::CITY_ID;
		}

		if ($this->aCity !== null && $this->aCity->getId() !== $v) {
			$this->aCity = null;
		}

		return $this;
	} // setCityId()

	/**
	 * Set the value of [state_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setStateId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->state_id !== $v) {
			$this->state_id = $v;
			$this->modifiedColumns[] = ClientPeer::STATE_ID;
		}

		if ($this->aState !== null && $this->aState->getId() !== $v) {
			$this->aState = null;
		}

		return $this;
	} // setStateId()

	/**
	 * Set the value of [zipcode_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setZipcodeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->zipcode_id !== $v) {
			$this->zipcode_id = $v;
			$this->modifiedColumns[] = ClientPeer::ZIPCODE_ID;
		}

		if ($this->aZipcode !== null && $this->aZipcode->getId() !== $v) {
			$this->aZipcode = null;
		}

		return $this;
	} // setZipcodeId()

	/**
	 * Set the value of [telephone1] column.
	 * 
	 * @param      string $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setTelephone1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telephone1 !== $v) {
			$this->telephone1 = $v;
			$this->modifiedColumns[] = ClientPeer::TELEPHONE1;
		}

		return $this;
	} // setTelephone1()

	/**
	 * Set the value of [telephone2] column.
	 * 
	 * @param      string $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setTelephone2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telephone2 !== $v) {
			$this->telephone2 = $v;
			$this->modifiedColumns[] = ClientPeer::TELEPHONE2;
		}

		return $this;
	} // setTelephone2()

	/**
	 * Set the value of [school] column.
	 * 
	 * @param      string $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setSchool($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->school !== $v) {
			$this->school = $v;
			$this->modifiedColumns[] = ClientPeer::SCHOOL;
		}

		return $this;
	} // setSchool()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = ClientPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [family_size] column.
	 * 
	 * @param      int $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setFamilySize($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->family_size !== $v) {
			$this->family_size = $v;
			$this->modifiedColumns[] = ClientPeer::FAMILY_SIZE;
		}

		return $this;
	} // setFamilySize()

	/**
	 * Set the value of [city_area] column.
	 * 
	 * @param      string $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setCityArea($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->city_area !== $v) {
			$this->city_area = $v;
			$this->modifiedColumns[] = ClientPeer::CITY_AREA;
		}

		return $this;
	} // setCityArea()

	/**
	 * Set the value of [service_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Client The current object (for fluent API support)
	 */
	public function setServiceId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->service_id !== $v) {
			$this->service_id = $v;
			$this->modifiedColumns[] = ClientPeer::SERVICE_ID;
		}

		if ($this->aService !== null && $this->aService->getId() !== $v) {
			$this->aService = null;
		}

		return $this;
	} // setServiceId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->last_name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->first_name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->parent_guardian_name = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->address_line = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->city_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->state_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->zipcode_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->telephone1 = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->telephone2 = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->school = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->email = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->family_size = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->city_area = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->service_id = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 15; // 15 = ClientPeer::NUM_COLUMNS - ClientPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Client object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCity !== null && $this->city_id !== $this->aCity->getId()) {
			$this->aCity = null;
		}
		if ($this->aState !== null && $this->state_id !== $this->aState->getId()) {
			$this->aState = null;
		}
		if ($this->aZipcode !== null && $this->zipcode_id !== $this->aZipcode->getId()) {
			$this->aZipcode = null;
		}
		if ($this->aService !== null && $this->service_id !== $this->aService->getId()) {
			$this->aService = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ClientPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCity = null;
			$this->aState = null;
			$this->aZipcode = null;
			$this->aService = null;
			$this->collClientVolunteerMaps = null;
			$this->lastClientVolunteerMapCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseClient:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ClientPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseClient:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseClient:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ClientPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseClient:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ClientPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCity !== null) {
				if ($this->aCity->isModified() || $this->aCity->isNew()) {
					$affectedRows += $this->aCity->save($con);
				}
				$this->setCity($this->aCity);
			}

			if ($this->aState !== null) {
				if ($this->aState->isModified() || $this->aState->isNew()) {
					$affectedRows += $this->aState->save($con);
				}
				$this->setState($this->aState);
			}

			if ($this->aZipcode !== null) {
				if ($this->aZipcode->isModified() || $this->aZipcode->isNew()) {
					$affectedRows += $this->aZipcode->save($con);
				}
				$this->setZipcode($this->aZipcode);
			}

			if ($this->aService !== null) {
				if ($this->aService->isModified() || $this->aService->isNew()) {
					$affectedRows += $this->aService->save($con);
				}
				$this->setService($this->aService);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ClientPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ClientPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ClientPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collClientVolunteerMaps !== null) {
				foreach ($this->collClientVolunteerMaps as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCity !== null) {
				if (!$this->aCity->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCity->getValidationFailures());
				}
			}

			if ($this->aState !== null) {
				if (!$this->aState->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aState->getValidationFailures());
				}
			}

			if ($this->aZipcode !== null) {
				if (!$this->aZipcode->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aZipcode->getValidationFailures());
				}
			}

			if ($this->aService !== null) {
				if (!$this->aService->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aService->getValidationFailures());
				}
			}


			if (($retval = ClientPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collClientVolunteerMaps !== null) {
					foreach ($this->collClientVolunteerMaps as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ClientPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getLastName();
				break;
			case 2:
				return $this->getFirstName();
				break;
			case 3:
				return $this->getParentGuardianName();
				break;
			case 4:
				return $this->getAddressLine();
				break;
			case 5:
				return $this->getCityId();
				break;
			case 6:
				return $this->getStateId();
				break;
			case 7:
				return $this->getZipcodeId();
				break;
			case 8:
				return $this->getTelephone1();
				break;
			case 9:
				return $this->getTelephone2();
				break;
			case 10:
				return $this->getSchool();
				break;
			case 11:
				return $this->getEmail();
				break;
			case 12:
				return $this->getFamilySize();
				break;
			case 13:
				return $this->getCityArea();
				break;
			case 14:
				return $this->getServiceId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ClientPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getLastName(),
			$keys[2] => $this->getFirstName(),
			$keys[3] => $this->getParentGuardianName(),
			$keys[4] => $this->getAddressLine(),
			$keys[5] => $this->getCityId(),
			$keys[6] => $this->getStateId(),
			$keys[7] => $this->getZipcodeId(),
			$keys[8] => $this->getTelephone1(),
			$keys[9] => $this->getTelephone2(),
			$keys[10] => $this->getSchool(),
			$keys[11] => $this->getEmail(),
			$keys[12] => $this->getFamilySize(),
			$keys[13] => $this->getCityArea(),
			$keys[14] => $this->getServiceId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ClientPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setLastName($value);
				break;
			case 2:
				$this->setFirstName($value);
				break;
			case 3:
				$this->setParentGuardianName($value);
				break;
			case 4:
				$this->setAddressLine($value);
				break;
			case 5:
				$this->setCityId($value);
				break;
			case 6:
				$this->setStateId($value);
				break;
			case 7:
				$this->setZipcodeId($value);
				break;
			case 8:
				$this->setTelephone1($value);
				break;
			case 9:
				$this->setTelephone2($value);
				break;
			case 10:
				$this->setSchool($value);
				break;
			case 11:
				$this->setEmail($value);
				break;
			case 12:
				$this->setFamilySize($value);
				break;
			case 13:
				$this->setCityArea($value);
				break;
			case 14:
				$this->setServiceId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ClientPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setLastName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFirstName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setParentGuardianName($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAddressLine($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCityId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setStateId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setZipcodeId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setTelephone1($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setTelephone2($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setSchool($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setEmail($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setFamilySize($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setCityArea($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setServiceId($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ClientPeer::DATABASE_NAME);

		if ($this->isColumnModified(ClientPeer::ID)) $criteria->add(ClientPeer::ID, $this->id);
		if ($this->isColumnModified(ClientPeer::LAST_NAME)) $criteria->add(ClientPeer::LAST_NAME, $this->last_name);
		if ($this->isColumnModified(ClientPeer::FIRST_NAME)) $criteria->add(ClientPeer::FIRST_NAME, $this->first_name);
		if ($this->isColumnModified(ClientPeer::PARENT_GUARDIAN_NAME)) $criteria->add(ClientPeer::PARENT_GUARDIAN_NAME, $this->parent_guardian_name);
		if ($this->isColumnModified(ClientPeer::ADDRESS_LINE)) $criteria->add(ClientPeer::ADDRESS_LINE, $this->address_line);
		if ($this->isColumnModified(ClientPeer::CITY_ID)) $criteria->add(ClientPeer::CITY_ID, $this->city_id);
		if ($this->isColumnModified(ClientPeer::STATE_ID)) $criteria->add(ClientPeer::STATE_ID, $this->state_id);
		if ($this->isColumnModified(ClientPeer::ZIPCODE_ID)) $criteria->add(ClientPeer::ZIPCODE_ID, $this->zipcode_id);
		if ($this->isColumnModified(ClientPeer::TELEPHONE1)) $criteria->add(ClientPeer::TELEPHONE1, $this->telephone1);
		if ($this->isColumnModified(ClientPeer::TELEPHONE2)) $criteria->add(ClientPeer::TELEPHONE2, $this->telephone2);
		if ($this->isColumnModified(ClientPeer::SCHOOL)) $criteria->add(ClientPeer::SCHOOL, $this->school);
		if ($this->isColumnModified(ClientPeer::EMAIL)) $criteria->add(ClientPeer::EMAIL, $this->email);
		if ($this->isColumnModified(ClientPeer::FAMILY_SIZE)) $criteria->add(ClientPeer::FAMILY_SIZE, $this->family_size);
		if ($this->isColumnModified(ClientPeer::CITY_AREA)) $criteria->add(ClientPeer::CITY_AREA, $this->city_area);
		if ($this->isColumnModified(ClientPeer::SERVICE_ID)) $criteria->add(ClientPeer::SERVICE_ID, $this->service_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ClientPeer::DATABASE_NAME);

		$criteria->add(ClientPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Client (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setLastName($this->last_name);

		$copyObj->setFirstName($this->first_name);

		$copyObj->setParentGuardianName($this->parent_guardian_name);

		$copyObj->setAddressLine($this->address_line);

		$copyObj->setCityId($this->city_id);

		$copyObj->setStateId($this->state_id);

		$copyObj->setZipcodeId($this->zipcode_id);

		$copyObj->setTelephone1($this->telephone1);

		$copyObj->setTelephone2($this->telephone2);

		$copyObj->setSchool($this->school);

		$copyObj->setEmail($this->email);

		$copyObj->setFamilySize($this->family_size);

		$copyObj->setCityArea($this->city_area);

		$copyObj->setServiceId($this->service_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getClientVolunteerMaps() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addClientVolunteerMap($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Client Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ClientPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ClientPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a City object.
	 *
	 * @param      City $v
	 * @return     Client The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCity(City $v = null)
	{
		if ($v === null) {
			$this->setCityId(NULL);
		} else {
			$this->setCityId($v->getId());
		}

		$this->aCity = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the City object, it will not be re-added.
		if ($v !== null) {
			$v->addClient($this);
		}

		return $this;
	}


	/**
	 * Get the associated City object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     City The associated City object.
	 * @throws     PropelException
	 */
	public function getCity(PropelPDO $con = null)
	{
		if ($this->aCity === null && ($this->city_id !== null)) {
			$c = new Criteria(CityPeer::DATABASE_NAME);
			$c->add(CityPeer::ID, $this->city_id);
			$this->aCity = CityPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCity->addClients($this);
			 */
		}
		return $this->aCity;
	}

	/**
	 * Declares an association between this object and a State object.
	 *
	 * @param      State $v
	 * @return     Client The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setState(State $v = null)
	{
		if ($v === null) {
			$this->setStateId(NULL);
		} else {
			$this->setStateId($v->getId());
		}

		$this->aState = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the State object, it will not be re-added.
		if ($v !== null) {
			$v->addClient($this);
		}

		return $this;
	}


	/**
	 * Get the associated State object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     State The associated State object.
	 * @throws     PropelException
	 */
	public function getState(PropelPDO $con = null)
	{
		if ($this->aState === null && ($this->state_id !== null)) {
			$c = new Criteria(StatePeer::DATABASE_NAME);
			$c->add(StatePeer::ID, $this->state_id);
			$this->aState = StatePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aState->addClients($this);
			 */
		}
		return $this->aState;
	}

	/**
	 * Declares an association between this object and a Zipcode object.
	 *
	 * @param      Zipcode $v
	 * @return     Client The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setZipcode(Zipcode $v = null)
	{
		if ($v === null) {
			$this->setZipcodeId(NULL);
		} else {
			$this->setZipcodeId($v->getId());
		}

		$this->aZipcode = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Zipcode object, it will not be re-added.
		if ($v !== null) {
			$v->addClient($this);
		}

		return $this;
	}


	/**
	 * Get the associated Zipcode object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Zipcode The associated Zipcode object.
	 * @throws     PropelException
	 */
	public function getZipcode(PropelPDO $con = null)
	{
		if ($this->aZipcode === null && ($this->zipcode_id !== null)) {
			$c = new Criteria(ZipcodePeer::DATABASE_NAME);
			$c->add(ZipcodePeer::ID, $this->zipcode_id);
			$this->aZipcode = ZipcodePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aZipcode->addClients($this);
			 */
		}
		return $this->aZipcode;
	}

	/**
	 * Declares an association between this object and a Service object.
	 *
	 * @param      Service $v
	 * @return     Client The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setService(Service $v = null)
	{
		if ($v === null) {
			$this->setServiceId(NULL);
		} else {
			$this->setServiceId($v->getId());
		}

		$this->aService = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Service object, it will not be re-added.
		if ($v !== null) {
			$v->addClient($this);
		}

		return $this;
	}


	/**
	 * Get the associated Service object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Service The associated Service object.
	 * @throws     PropelException
	 */
	public function getService(PropelPDO $con = null)
	{
		if ($this->aService === null && ($this->service_id !== null)) {
			$c = new Criteria(ServicePeer::DATABASE_NAME);
			$c->add(ServicePeer::ID, $this->service_id);
			$this->aService = ServicePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aService->addClients($this);
			 */
		}
		return $this->aService;
	}

	/**
	 * Clears out the collClientVolunteerMaps collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addClientVolunteerMaps()
	 */
	public function clearClientVolunteerMaps()
	{
		$this->collClientVolunteerMaps = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collClientVolunteerMaps collection (array).
	 *
	 * By default this just sets the collClientVolunteerMaps collection to an empty array (like clearcollClientVolunteerMaps());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initClientVolunteerMaps()
	{
		$this->collClientVolunteerMaps = array();
	}

	/**
	 * Gets an array of ClientVolunteerMap objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Client has previously been saved, it will retrieve
	 * related ClientVolunteerMaps from storage. If this Client is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ClientVolunteerMap[]
	 * @throws     PropelException
	 */
	public function getClientVolunteerMaps($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ClientPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collClientVolunteerMaps === null) {
			if ($this->isNew()) {
			   $this->collClientVolunteerMaps = array();
			} else {

				$criteria->add(ClientVolunteerMapPeer::CLIENT_ID, $this->id);

				ClientVolunteerMapPeer::addSelectColumns($criteria);
				$this->collClientVolunteerMaps = ClientVolunteerMapPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ClientVolunteerMapPeer::CLIENT_ID, $this->id);

				ClientVolunteerMapPeer::addSelectColumns($criteria);
				if (!isset($this->lastClientVolunteerMapCriteria) || !$this->lastClientVolunteerMapCriteria->equals($criteria)) {
					$this->collClientVolunteerMaps = ClientVolunteerMapPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastClientVolunteerMapCriteria = $criteria;
		return $this->collClientVolunteerMaps;
	}

	/**
	 * Returns the number of related ClientVolunteerMap objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ClientVolunteerMap objects.
	 * @throws     PropelException
	 */
	public function countClientVolunteerMaps(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ClientPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collClientVolunteerMaps === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ClientVolunteerMapPeer::CLIENT_ID, $this->id);

				$count = ClientVolunteerMapPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ClientVolunteerMapPeer::CLIENT_ID, $this->id);

				if (!isset($this->lastClientVolunteerMapCriteria) || !$this->lastClientVolunteerMapCriteria->equals($criteria)) {
					$count = ClientVolunteerMapPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collClientVolunteerMaps);
				}
			} else {
				$count = count($this->collClientVolunteerMaps);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ClientVolunteerMap object to this object
	 * through the ClientVolunteerMap foreign key attribute.
	 *
	 * @param      ClientVolunteerMap $l ClientVolunteerMap
	 * @return     void
	 * @throws     PropelException
	 */
	public function addClientVolunteerMap(ClientVolunteerMap $l)
	{
		if ($this->collClientVolunteerMaps === null) {
			$this->initClientVolunteerMaps();
		}
		if (!in_array($l, $this->collClientVolunteerMaps, true)) { // only add it if the **same** object is not already associated
			array_push($this->collClientVolunteerMaps, $l);
			$l->setClient($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Client is new, it will return
	 * an empty collection; or if this Client has previously
	 * been saved, it will retrieve related ClientVolunteerMaps from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Client.
	 */
	public function getClientVolunteerMapsJoinVolunteer($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ClientPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collClientVolunteerMaps === null) {
			if ($this->isNew()) {
				$this->collClientVolunteerMaps = array();
			} else {

				$criteria->add(ClientVolunteerMapPeer::CLIENT_ID, $this->id);

				$this->collClientVolunteerMaps = ClientVolunteerMapPeer::doSelectJoinVolunteer($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ClientVolunteerMapPeer::CLIENT_ID, $this->id);

			if (!isset($this->lastClientVolunteerMapCriteria) || !$this->lastClientVolunteerMapCriteria->equals($criteria)) {
				$this->collClientVolunteerMaps = ClientVolunteerMapPeer::doSelectJoinVolunteer($criteria, $con, $join_behavior);
			}
		}
		$this->lastClientVolunteerMapCriteria = $criteria;

		return $this->collClientVolunteerMaps;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collClientVolunteerMaps) {
				foreach ((array) $this->collClientVolunteerMaps as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collClientVolunteerMaps = null;
			$this->aCity = null;
			$this->aState = null;
			$this->aZipcode = null;
			$this->aService = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseClient:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseClient::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseClient
