# config/schema.yml
propel:
  _attributes:
    package: lib.model

  user:
    id:
      type: INTEGER
      required: true
      autoIncrement: true
      primaryKey: true
    email:
      type: VARCHAR
      size: 128
      index: unique
    user_name:
      type: VARCHAR
      size: 255
      index: unique
    password:
      type: CHAR
      size: 128
    salt:
      type: CHAR
      size: 64
    auth_token:
      type: CHAR
      size: 32
    created_at:
      type: TIMESTAMP
    _indexes:
      user_FI_1:
        - auth_token
      user_FI_2:
        - email
      user_FI_3:
        - user_name
  city:
    id:
      type: INTEGER
      required: true
      autoIncrement: true
      primaryKey: true
    city_name:
      type: VARCHAR
      size: 255
    _indexes:
      city_FI_1:
        - city_name

  zipcode:
    id:
      type: INTEGER
      required: true
      autoIncrement: true
      primaryKey: true
    zip_code:
      type: VARCHAR
      size: 32
      index: unique
    _indexes:
      zipcode_FI_1:
        - zip_code

  state:
    id:
      type: INTEGER
      required: true
      autoIncrement: true
      primaryKey: true
    state_name:
      type: VARCHAR
      size: 128
      index: unique
    state_abbreviation:
      type: VARCHAR
      size: 32
      index: unique
    _indexes:
      state_FI_1:
        - state_name
      state_FI_2:
        - state_abbreviation

  service:
    id:
      type: INTEGER
      required: true
      autoIncrement: true
      primaryKey: true
    service_name:
      type: VARCHAR
      size: 255
    _indexes:
      service_FI_1:
        - service_name

  volunteer:
    id:
      type: INTEGER
      required: true
      autoIncrement: true
      primaryKey: true
    last_name:
      type: VARCHAR
      size: 255
    first_name:
      type: VARCHAR
      size: 255
    address_line:
      type: VARCHAR
      size: 255
    city_id:
      type: INTEGER
    state_id:
      type: INTEGER
    zipcode_id:
      type: INTEGER
    telephone_home:
      type: VARCHAR
      size: 128
    telephone_cell:
      type: VARCHAR
      size: 128
    telephone_work:
      type: VARCHAR
      size: 128
    email:
      type: VARCHAR
      size: 255
      index: unique
    church:
      type: VARCHAR
      size: 255
    city_area:
      type: VARCHAR
      size: 255
    service_id:
      type: INTEGER
    _indexes:
      volunteer_FIKey_1:
        - church
      volunteer_FIKey_2:
        - email
      volunteer_FIKey_3:
        - city_area
      volunteer_FIKey_4:
        - last_name
      volunteer_FIKey_5:
        - first_name
    _foreignKeys:
      -
        foreignTable: city
        onDelete: setnull
        references:
          - { local: city_id, foreign: id }
      -
        foreignTable: state
        onDelete: setnull
        references:
          - { local: state_id , foreign: id }
      -
        foreignTable: zipcode
        onDelete: setnull
        references:
          - { local: zipcode_id , foreign: id }
      -
        foreignTable: service
        onDelete: setnull
        references:
          - { local: service_id , foreign: id }

  client:
    id:
      type: INTEGER
      required: true
      autoIncrement: true
      primaryKey: true
    last_name:
      type: VARCHAR
      size: 255
    first_name:
      type: VARCHAR
      size: 255
    parent_guardian_name:
      type: VARCHAR
      size: 255
    address_line:
      type: VARCHAR
      size: 255
    city_id:
      type: INTEGER
    state_id:
      type: INTEGER
    zipcode_id:
      type: INTEGER
    telephone1:
      type: VARCHAR
      size: 64
    telephone2:
      type: VARCHAR
      size: 64
    school:
      type: VARCHAR
      size: 255
    email:
      type: VARCHAR
      size: 255
      index: unique
    family_size:
      type: INTEGER
    city_area:
      type: VARCHAR
      size: 255
    service_id:
      type: INTEGER
    _indexes:
      client_FIKey_1:
        - last_name
      client_FIKey_2:
        - first_name
      client_FIKey_3:
        - school
      client_FIKey_4:
        - city_area
    _foreignKeys:
      -
        foreignTable: city
        onDelete: setnull
        references:
          - { local: city_id , foreign: id }
      -
        foreignTable: state
        onDelete: setnull
        references:
          - { local: state_id , foreign: id }
      -
        foreignTable: zipcode
        onDelete: setnull
        references:
          - { local: zipcode_id, foreign: id }
      -
        foreignTable: service
        onDelete: setnull
        references:
          - { local: service_id, foreign: id }


  client_volunteer_map:
    id:
      type: INTEGER
      required: true
      autoIncrement: true
      primaryKey: true
    client_id:
      type: INTEGER
    volunteer_id:
      type: INTEGER
    _foreignKeys:
      -
        foreignTable: client
        onDelete: setnull
        references:
          - { local: client_id , foreign: id }
      -
        foreignTable: volunteer
        onDelete: setnull
        references:
          - { local: volunteer_id , foreign: id }